-- BASE DE DATOS USADA POSTGRESQL

/* SENTENCIAS PARA CREAR CRM DB */
CREATE ROLE test WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'test';

CREATE DATABASE dbcrm
    WITH
    OWNER = test
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;


/* SENTENCIAS PARA CREAR BILL DB */
CREATE ROLE test WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'test';

CREATE DATABASE dbbill
    WITH
    OWNER = test
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;